### ISSUE TITLE
BaseTool inheritance

### ISSUE THREAD

**Issue by neph1** [zhound420/rabbitmq#14]
One thing I notice from glancing at the code (I'm on my phone ATM) is that RabbitMqTool doesn't follow the structure the built in tools do. Look for example at how the email tool is built up, one class for the input (BaseModel) and one for the tool (BaseTool). I tried to follow the architecture of the existing tools closely (and still failed). Good luck!

**Comment by zhound420** [comment]
Thank you @neph1 . I got it register in the app and now it shows up as a toolkit properly. Almost there. Thanks again.

**Comment by zhound420** [comment]
comment
